---
- name : Configuring Jenkins CI server and nexus3-oss 
  hosts: jenkins
  sudo : True
  roles: 
    - git
    - geerlingguy.jenkins
    - savoirfairelinux.nexus3-oss

- hosts: database
  roles:
    - role: geerlingguy.mysql
      become: yes
