---

  - name: Ensure app folder exists
    file:
      path: /opt/app
      state: directory
      mode: u+rwx
      follow: true

  - name: Download war file
    get_url:
      url: http://localhost:8081/repository/todoapp-release/com/somecompany/TodoDemo/{{ version }}/TodoDemo-{{ version }}.war
      dest: /opt/app/TodoDemo.war
      url_username: "{{ username }}"
      url_password: "{{ password }}"

  - name: Kill TodoApp process if running
    shell: "ps -aef | grep TodoDemo | grep -v grep | awk '{print $2}' | xargs kill -9"
    shell: "sleep 20"

  - name: Start application
    shell : "sh start.sh"