---

  - name: Ensure app folder exists
    file:
      path: /opt/app
      state: directory
      mode: u+rwx
      follow: true

  - name: Download war file
    get_url:
      url: http://localhost:8081/repository/todoapp-release/com/somecompany/TodoDemo/11/TodoDemo-11.war
      dest: /opt/app/TodoDemo.war
      url_username: admin
      url_password: admin123

  - name: Kill TodoApp process if running
    shell: "ps -aef | grep TodoDemo | grep -v grep | awk '{print $2}' | xargs kill -9"

  - name: Start application
    shell : "nohup java -Dserver.port=5000 -jar /opt/app/TodoDemo.war >> /opt/app/app.log &"